# Generated by Django 2.1.7 on 2019-02-24 16:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='listing',
            old_name='Company',
            new_name='company',
        ),
        migrations.RenameField(
            model_name='listing',
            old_name='Description',
            new_name='description',
        ),
        migrations.RenameField(
            model_name='listing',
            old_name='Role',
            new_name='role',
        ),
    ]
